server:
  port: 8080

spring:
  application:
    name: client
  profiles:
    active: local

# mybatis-plus相关配置
mybatis-plus:
  mapper-locations: classpath:/mapper/**.xml
  configuration:
    map-underscore-to-camel-case: true  # 驼峰转换
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id # 主键生成策略(雪花算法)
      update-strategy: not_null # 更新策略

# swagger 增强文档相配置
knife4j:
  enable: true
  openapi:
    title: 在线判题系统后端(client)
    description: '在线判题系统'
    email: 3136188547@qq.com
    concat: 大菜鸟
    version: v4.0
    license: Apache 2.0
    group:
      test1:
        group-name: 模板
        api-rule: package
        api-rule-resources:
          - com.coderank.controller